name: Update JSON File

on:
  workflow_dispatch:  # Allows manual trigger from JavaScript
  push:
    branches:
      - main

permissions:
  contents: write  # Grants permission to write to the repository

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update JSON File
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}  # Use the stored secret token
        run: |
          COMMIT_MESSAGE="Automated JSON Update"
          FILE_PATH="judging_data.json"

          # Get file SHA
          SHA=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/MrCodable/YTACjudging/contents/$FILE_PATH | jq -r '.sha')

          # Upload the new JSON file
          curl -X PUT -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MrCodable/YTACjudging/contents/$FILE_PATH \
            -d @<(cat <<EOF
          {
            "message": "$COMMIT_MESSAGE",
            "content": "$(base64 -w 0 $FILE_PATH)",
            "sha": "$SHA"
          }
          EOF
          )
