name: Update JSON File

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually from JS
  push:
    branches:
      - main  # Runs when a commit is pushed to the main branch

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update JSON File
        run: |
          echo '${{ secrets.TOKEN }}' | gh auth login --with-token
          curl -X PUT \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MrCodable/YTACjudging/contents/judging_data.json \
            -d '{
              "message": "Automated JSON Update",
              "content": "'"$(base64 -w 0 judging_data.json)"'",
              "sha": "$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MrCodable/YTACjudging/contents/judging_data.json | jq -r '.sha')"
            }'
