# workflow_dispatch:  # Allows the workflow to be triggered manually from JS

name: Update JSON File

on:
  push:
    branches:
      - main  # Runs when a commit is pushed to the main branch

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store base64 content
        id: store-content
        run: echo "::set-output name=content::$(base64 -w 0 judging_data.json)"

      - name: Get file SHA
        id: get-sha
        run: |
          SHA=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MrCodable/YTACjudging/contents/judging_data.json | jq -r '.sha')
          echo "::set-output name=sha::$SHA"

      - name: Update JSON File
        run: |
          curl -X PUT \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/MrCodable/YTACjudging/contents/judging_data.json \
          -d '{
            "message": "Automated JSON Update",
            "content": "${{ steps.store-content.outputs.content }}",
            "sha": "${{ steps.get-sha.outputs.sha }}"
          }'
