name: Update JSON File

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load GitHub Token
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "GitHub Token Loaded"

      - name: Decode and Save JSON
        run: |
          echo '${{ secrets.JSON_CONTENT }}' | base64 --decode > judging_data.json

      - name: Upload Updated JSON to GitHub
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          COMMIT_MESSAGE="Automated JSON Update"
          BRANCH_NAME="main"
          FILE_PATH="judging_data.json"

          # Get file SHA
          SHA=$(curl -s -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/MrCodable/YTACjudging/contents/$FILE_PATH | jq -r '.sha')

          # Upload the new JSON file
          curl -X PUT -H "Authorization: token $GH_TOKEN" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MrCodable/YTACjudging/contents/$FILE_PATH \
            -d @<(cat <<EOF
          {
            "message": "$COMMIT_MESSAGE",
            "content": "$(base64 -w 0 $FILE_PATH)",
            "sha": "$SHA"
          }
          EOF
          )
